# utils/carga_generica.py
from PySide6.QtCore import QDate

def get_carga_generica(dispositivo):
    genericos = {
        "Computadora": {
            "nombre": "Juan Pérez",
            "telefono": "123456789",
            "modelo": "Modelo X",
            "placa": "ABC123",
            "pantalla": "15.6 pulgadas",
            "correo": "ejemplo@correo.com",
            "sistema_operativo": "Windows 11",
            "ram": "16GB",
            "procesador": "Intel i7",
            "memoria": "512GB SSD",
            "fuente": "500W",
            "tarjeta_grafica": "NVIDIA GTX 1650",
            "garantia": QDate.currentDate(),
            "fecha_de_ingreso": QDate.currentDate(),
            "precio": "5.000.000",
            "estado": "New"
        },
        "Impresora": {
            "nombre": "María López",
            "telefono": "0987654321",
            "modelo": "Epson L3150",
            "correo": "maria@example.com",
            "estado_general": "Funciona correctamente",
            "tipo_impresora": "Multifunción",
            "conectividad": "Wi-Fi",
            "tipo_tinta": "Tinta continua",
            "uso_estimado": "Uso doméstico moderado",
            "garantia": QDate.currentDate(),
            "fecha_de_ingreso": QDate.currentDate(),
            "precio": "3.500.000",
            "estado": "En revisión",
            "marca": "Epson",
            "placa": "XYZ456",
            "numero_serie": "SN-987654321"
        },
        "Notebook": {
            "nombre": "Carlos Ruiz",
            "telefono": "1122334455",
            "modelo": "HP Pavilion",
            "correo": "carlos@notebook.com",
            "estado_cargador": "Nuevo",
            "tarjeta_grafica": "Intel UHD",
            "garantia": QDate.currentDate(),
            "fecha_de_ingreso": QDate.currentDate(),
            "procesador": "Intel i5",
            "placa": "NB123",
            "memoria": "256GB SSD",
            "pantalla": "14 pulgadas",
            "tim": "TIM123",
            "ram": "8GB",
            "estado": "New",
            "notas": "Sin observaciones"
        },
        "Celular": {
            "nombre": "Ana Torres",
            "telefono": "2233445566",
            "modelo": "Samsung S21",
            "correo": "ana@celular.com",
            "estado_cargador": "Usado",
            "bateria": "80%",
            "memoria": "128GB",
            "placa": "CEL123",
            "pantalla": "6.2 pulgadas",
            "sistema_operativo": "Android 12",
            "ram": "6GB",
            "estado": "Used",
            "fecha_de_ingreso": QDate.currentDate(),
            "garantia": QDate.currentDate(),
            "notas": "Sin observaciones"
        },
        "Tablet": {
            "nombre": "Lucas Díaz",
            "telefono": "3344556677",
            "modelo": "iPad Pro",
            "correo": "lucas@tablet.com",
            "estado_cargador": "Nuevo",
            "bateria": "100%",
            "memoria": "256GB",
            "placa": "TAB123",
            "pantalla": "12.9 pulgadas",
            "sistema_operativo": "iPadOS",
            "ram": "8GB",
            "estado": "New",
            "fecha_de_ingreso": QDate.currentDate(),
            "garantia": QDate.currentDate(),
            "notas": "Sin observaciones"
        },
        "PlayStation": {
            "nombre": "Javier Pérez",
            "telefono": "5566778899",
            "modelo": "PS5",
            "correo": "javier@ps.com",
            "procesador": "AMD Ryzen",
            "cantidad_mandos": 2,
            "memoria": "825GB SSD",
            "mandos_estado": "Nuevo",
            "pantalla": "4K",
            "sistema_operativo": "PlayStation OS",
            "ram": "16GB",
            "estado": "New",
            "fecha_de_ingreso": QDate.currentDate(),
            "garantia": QDate.currentDate()
        },
        "PS3Consola": {
            "nombre": "Martín López",
            "telefono": "6677889900",
            "modelo": "PS3",
            "correo": "martin@ps3.com",
            "procesador": "Cell Broadband Engine",
            "cantidad_mandos": 2,
            "memoria": "320GB HDD",
            "mandos_estado": "Usado",
            "pantalla": "Full HD",
            "sistema_operativo": "PlayStation OS",
            "ram": "256MB",
            "estado": "Used",
            "fecha_de_ingreso": QDate.currentDate(),
            "garantia": QDate.currentDate()
        },
        "Personalizado": {
            "nombre": "Cliente Personalizado",
            "telefono": "000000000",
            "modelo": "Modelo Personalizado",
            "correo": "personalizado@correo.com",
            "fecha_de_ingreso": QDate.currentDate(),
            "garantia": QDate.currentDate(),
            "estado": "New"
        }
    }
    return genericos.get(dispositivo, genericos["Personalizado"])
